### ISSUE TITLE
fn is not a function

### ISSUE THREAD

**Issue by ansarizafar** [niftylettuce/winston-raven-sentry#1]
I am getting this error
![image](https://user-images.githubusercontent.com/5788284/32403990-9d2a1f10-c168-11e7-8f05-bc2ba427f8e8.png)

**Comment by dcharbonnier** [comment]
if you want a better implementation with more support you can try https://www.npmjs.com/package/raven-winston-ya

**Comment by lwiecek** [comment]
I am having the same issue. Do you also have `"winston": "^3.0.0-rc0"` in `package.json`? I haven't checked what happens when I downgrade to  `"winston": "^2.4.0"`?

**Comment by lwiecek** [comment]
Downgrading `winston` to `2.4.0` fixes this problem.

**Comment by alexpts** [comment]
Can I help add support for winston@next?

**Comment by niftylettuce** [comment]
This package is deprecated and a better alternative has been created, please use Cabin: https://cabinjs.com
