### ISSUE TITLE
Any way to retrieve eventId?

### ISSUE THREAD

**Issue by Fuco1** [niftylettuce/winston-raven-sentry#2]
`Raven.captureException` provides the `eventId` which is associated with the event.  It is sometimes useful to show this to users so that they can reference to the given event and the developers have easier time finding the report.

https://docs.sentry.io/clients/node/usage/ shows how to obtain it.  Is there any way to extend this package to make it available?

**Comment by niftylettuce** [comment]
This package is deprecated and a better alternative has been created, please use Cabin: https://cabinjs.com
