### ISSUE TITLE
Is package still maintained?

### ISSUE THREAD

**Issue by VinceOPS** [niftylettuce/winston-raven-sentry#3]
Hi @niftylettuce, thanks for your package, it's working well until now.

Just wondering, are you still maintaining it, and would you be receptive to PRs? I'd like to suggest a typedef file (for people using the module with typescript) and an update of Raven (to 2.4).

Thanks :-).

**Comment by niftylettuce** [comment]
Open to PRs and adding you as a maintainer

**Comment by stanogurnik** [comment]
Raven client updated in #6

**Comment by stanogurnik** [comment]
IMHO we at @storyous would love to maintain and push this package further :)

**Comment by carcinocron** [comment]
I think Sentry is moving towards namespaced packages, how will this work with winston or winston 3?

https://github.com/getsentry/sentry-javascript#supported-platforms

```
import { init, captureMessage } from '@sentry/browser'; // or '@sentry/node'

init({
  dsn: '__DSN__',
  // ...
});

captureMessage('Hello, world!');
```

**Comment by spruce-bruce** [comment]
I set up a public repo that we'll be using that uses the new node sentry SDK and will be compatible with winston 3.0 (I'm doing 2.x first cause I need to support 2.x as well)

https://github.com/synapsestudios/winston-sentry

**Comment by danielvaijk** [comment]
@spruce-bruce any progress?

**Comment by spruce-bruce** [comment]
Yep! Sorry the repo looks bare because everything's in a 1.0 branch still. It is published to npm if you're willing to start using it: `npm i @synapsestudios/winston-sentry` and you can checkout the README here https://github.com/synapsestudios/winston-sentry/tree/release/v1.0.0

I've implemented that with winston 2, because that's what i'm using in prod right now, and will have a 2.0 coming out shortly for winston 3.

**Comment by niftylettuce** [comment]
Sorry, I refuse to support Sentry (and other similar services like Bugsnag) because of a specific security issue with their tools/packages.

To solve my problems, I built my own logging platform and utilities.

CabinJS at https://cabinjs.com

**Comment by danielvaijk** [comment]
@niftylettuce awesome! I'll likely be using your approach rather than a disconnected combo of Winston/Morgan/Sentry.

**Comment by rasmuslp** [comment]
> Sorry, I refuse to support Sentry (and other similar services like Bugsnag) because of a specific security issue with their tools/packages.

With that said, would you at least update the description / README? The "maintained" part is very misleading.
