### ISSUE TITLE
Add support for winston@3.0.0

### ISSUE THREAD

**Issue by TuxGit** [niftylettuce/winston-raven-sentry#7]
Tested winston@3.0.0rc5 and its not work.

**Comment by shikaan** [comment]
Any updates?

**Comment by Vadorequest** [comment]
@niftylettuce Do you plan on adding support anytime soon? :)

If you don't have time, any guidelines for a PR?

**Comment by conscott** [comment]
You can switch to this: https://github.com/aandrewww/winston-sentry-raven-transport

**Comment by niftylettuce** [comment]
I have built my own service, https://cabinjs.com
