### ISSUE TITLE
captureBreadcrumb apparently doesn't work

### ISSUE THREAD

**Issue by tomaz-easybi** [niftylettuce/winston-raven-sentry#8]
For example, if do:

logger.transports.sentry.raven.captureBreadcrumb({
  message: "test breadcrumb",
  data: {
    application: { state: "initializing" }
  }
});
logger.error("test test, delete me 2");

The error will show up in sentry, but the breadcrumb will not.

**Comment by BnayaZil** [comment]
Happens for me as well, someone knows something? breadcrumbs just stop being sent.

**Comment by niftylettuce** [comment]
This package is deprecated and a better alternative has been created, please use Cabin: https://cabinjs.com
