### ISSUE TITLE
undefined is a legacy winston transport

### ISSUE THREAD

**Issue by AdamGerthel** [niftylettuce/winston-raven-sentry#9]
I've implemented the module as per readme instructions (via `winston.add`), but I'm getting the follow warning when the server starts:

```
undefined is a legacy winston transport. Consider upgrading: 
- Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
```

The logging works, but the message implies that there is something wrong.

Im using the following versions:

Node: 10.15.3
Winston: 3.2.1
Winston-raven-sentry: 2.0.0

**Comment by AdamGerthel** [comment]
Update: I moved to https://github.com/aandrewww/winston-sentry-raven-transport instead

**Comment by niftylettuce** [comment]
This package is deprecated and a better alternative has been created, please use Cabin: https://cabinjs.com
